config/routes.rb
Rails.application.routes.draw do
  root 'gists#index'
  devise_for :users
  resources :gists do
    resources :comments, only: [:create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gist
  belongs_to :user

  validates :body, presence: true
end

app/models/gist.rb
class Gist < ActiveRecord::Base
  validates :content, :description, presence: true

  default_scope  { order(created_at: :desc) }
  scope :opened, -> { where(private: false) }
  scope :closed, -> { where(private: true) }

  belongs_to :user
  has_many :comments

  def highlighted(lines: nil)
    code = if lines
      content.lines.take(lines).join
    else
      content
    end

    if language.blank?
      Pygments.highlight(code, options: {encoding: 'utf-8'}).html_safe
    else
      Pygments.highlight(code,
        lexer: Pygments.lexers[language][:aliases][0],
        options: {encoding: 'utf-8'}).html_safe
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :json

  def create
    @user = current_user
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params.merge({user_id: @user.id}))
    redirect_to gist_path(@gist)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body, :gist_id, :user_id)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_gist, only: [:edit, :update, :destroy]

  def index
    @gists = Gist.opened
  end

  def show
    @gist = Gist.find(params[:id])
  end

  def new
    @gist = current_user.gists.new
  end

  def edit
  end

  def create
    @gist = current_user.gists.create(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = current_user.gists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:description, :content, :language, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end

  def gravatar_img(email)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    image_tag("http://gravatar.com/avatar/#{gravatar_id}.png?s=140", height: 50, height: 50)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/comments/_form.slim
= form_for([@gist, @gist.comments.build]) do |f|
  .form-group
    = f.text_area :body, :rows => 10, class: 'form-control'
  .actions
    = f.submit class: 'btn btn-success pull-right'

app/views/comments/_show.slim
#comments
  - @gist.comments.each do |comment|
    .row
      .col-md-1= gravatar_img(comment.user.email)
      .col-md-11
        div class="panel panel-info"
          .panel-heading
            strong
              = comment.user.email
            = " commented #{time_ago_in_words(comment.created_at)} ago"
          .panel-body
            == comment.body.gsub(/\n/, "</br>")

app/views/gists/_form.slim
.col-md-2

.col-md-8
  = form_for(@gist) do |f|
    -if @gist.errors.any?
      div class="panel panel-danger"
        .panel-heading
          = "#{pluralize(@gist.errors.count, 'error')} prohibited this gist from being saved:"
        .panel-body
          ul
            - @gist.errors.full_messages.each do |message|
              li= message
    .row
      .col-md-8
        .form-group
          = f.text_field :description, class: 'form-control', placeholder: 'description'
      .col-md-4
        .form-group
          = f.select :language, Pygments.lexers.collect { |l, k| Pygments.lexers[l][:name] }, {include_blank: 'Auto'}, class: 'form-control'

    .form-group
      = f.text_area :content, :rows => 20, class: 'form-control'
    .checkbox
      label
        = f.check_box :private
        = "Private"
    .actions
      = f.submit class: 'btn btn-success pull-right'

.col-md-2

app/views/gists/edit.slim
= render 'form'

app/views/gists/index.slim
.row
  .col-md-2
  .col-md-8
    - @gists.each do |gist|
      .gist
        .gist-meta
          .row
            .col-md-1.gist-avatar = gravatar_img(gist.user.email)
            .col-md-11
              .pull-right
                a.comment-counter href="{gist_path(gist)}#comments"
                  span class="glyphicon glyphicon-comment"
                  = " #{gist.comments.count} comments"
              .gist-description = gist.description
              .gist-timestamp= "#{time_ago_in_words(gist.created_at)} ago by #{gist.user.email}"

        .gist-content
          a.gist href=gist_path(gist)
            table
              tbody
                tr
                  td.line-numbers
                    - gist.content.lines.take(10).count.times do |i|
                      span.line-number = i + 1
                  td.line-data
                    = gist.highlighted(lines: 10)
  .col-md-2

app/views/gists/new.slim
= render 'form'

app/views/gists/show.slim
.col-md-2
.col-md-8
  .gist
    .gist-meta
      .row
        .col-md-1.gist-avatar= gravatar_img(@gist.user.email)
        .col-md-6
          .gist-description= @gist.description
          .gist-timestamp= "#{time_ago_in_words(@gist.created_at)} ago by #{@gist.user.email}"

        .col-md-5
          .pull-right
            - if user_signed_in? && current_user.id == @gist.user_id 
              = link_to 'Edit', edit_gist_path(@gist), class: 'btn btn-default'
              = " "
              = link_to 'Destroy', @gist, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-danger'

    .gist-content
      table
        tbody
          tr
            td.line-numbers
              - @gist.content.lines.count.times do |i|
                span.line-number = i + 1
            td.line-data
              = @gist.highlighted

    = render 'comments/show', locals: {comments: @gist.comments}
    = render 'comments/form', locals: {gist: @gist} if user_signed_in?
.col-md-2

app/views/layouts/application.slim
doctype html
html
  head
    title Gist clone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container
      .row = render 'shared/header'
      .row = render partial: 'shared/flash_messages', flash: flash
      .row = yield
      </br>
      .row = render 'shared/footer'

app/views/shared/_flash_messages.slim
.row
  .col-md-2
  .col-md-8
    - flash.each do |type, message|
      div class="alert #{alert_class_for(type)} alert-dismissible fade in"
        button.close type="button" data-dismiss="alert"
          span aria-hidden="true" &times;
          span.sr-only Close
        = message
  .col-md-2

app/views/shared/_footer.slim
.col-md-2 &nbsp;
.col-md-8
  #footer
    = "source code"
    a href="https://github.com/ryuk/rails-gist-clone"  here
.col-md-2 &nbsp;

app/views/shared/_header.slim
.col-md-2

.col-md-8
  .page-header
    #page-header
      #header
        #title
          = link_to 'Make it stupid simple', root_path
      .menu
        - if user_signed_in?
          = link_to 'New Gist', new_gist_path, class: 'pull-left'
          = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          = link_to 'Sign in', new_user_session_path
.col-md-2